
server:
port: 8080

spring:
 application:
  name: db_service
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://${SERVER:localhost}:${PORT:5444}/${DB_NAME:service_db}
  username: postgres
  password: root
 jpa:
  hibernate:
   ddl-auto: ${HIBERNATE_DDL:create}
   show-sql: true
   properties:
    hibernate:
     format_sql: true
     enable_lazy_load_no_trans: false